/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FredAdd {
    }
    interface FredHome {
    }
    interface FredRoot {
    }
}
declare global {
    interface HTMLFredAddElement extends Components.FredAdd, HTMLStencilElement {
    }
    var HTMLFredAddElement: {
        prototype: HTMLFredAddElement;
        new (): HTMLFredAddElement;
    };
    interface HTMLFredHomeElement extends Components.FredHome, HTMLStencilElement {
    }
    var HTMLFredHomeElement: {
        prototype: HTMLFredHomeElement;
        new (): HTMLFredHomeElement;
    };
    interface HTMLFredRootElement extends Components.FredRoot, HTMLStencilElement {
    }
    var HTMLFredRootElement: {
        prototype: HTMLFredRootElement;
        new (): HTMLFredRootElement;
    };
    interface HTMLElementTagNameMap {
        "fred-add": HTMLFredAddElement;
        "fred-home": HTMLFredHomeElement;
        "fred-root": HTMLFredRootElement;
    }
}
declare namespace LocalJSX {
    interface FredAdd {
    }
    interface FredHome {
    }
    interface FredRoot {
    }
    interface IntrinsicElements {
        "fred-add": FredAdd;
        "fred-home": FredHome;
        "fred-root": FredRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fred-add": LocalJSX.FredAdd & JSXBase.HTMLAttributes<HTMLFredAddElement>;
            "fred-home": LocalJSX.FredHome & JSXBase.HTMLAttributes<HTMLFredHomeElement>;
            "fred-root": LocalJSX.FredRoot & JSXBase.HTMLAttributes<HTMLFredRootElement>;
        }
    }
}
