/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FredAdd {
    }
    interface FredButton {
        "url": string;
    }
    interface FredHome {
    }
    interface FredIcon {
        "name": string;
        "size": 's' | 'm';
    }
    interface FredNav {
    }
    interface FredPage {
    }
    interface FredRoot {
    }
}
declare global {
    interface HTMLFredAddElement extends Components.FredAdd, HTMLStencilElement {
    }
    var HTMLFredAddElement: {
        prototype: HTMLFredAddElement;
        new (): HTMLFredAddElement;
    };
    interface HTMLFredButtonElement extends Components.FredButton, HTMLStencilElement {
    }
    var HTMLFredButtonElement: {
        prototype: HTMLFredButtonElement;
        new (): HTMLFredButtonElement;
    };
    interface HTMLFredHomeElement extends Components.FredHome, HTMLStencilElement {
    }
    var HTMLFredHomeElement: {
        prototype: HTMLFredHomeElement;
        new (): HTMLFredHomeElement;
    };
    interface HTMLFredIconElement extends Components.FredIcon, HTMLStencilElement {
    }
    var HTMLFredIconElement: {
        prototype: HTMLFredIconElement;
        new (): HTMLFredIconElement;
    };
    interface HTMLFredNavElement extends Components.FredNav, HTMLStencilElement {
    }
    var HTMLFredNavElement: {
        prototype: HTMLFredNavElement;
        new (): HTMLFredNavElement;
    };
    interface HTMLFredPageElement extends Components.FredPage, HTMLStencilElement {
    }
    var HTMLFredPageElement: {
        prototype: HTMLFredPageElement;
        new (): HTMLFredPageElement;
    };
    interface HTMLFredRootElement extends Components.FredRoot, HTMLStencilElement {
    }
    var HTMLFredRootElement: {
        prototype: HTMLFredRootElement;
        new (): HTMLFredRootElement;
    };
    interface HTMLElementTagNameMap {
        "fred-add": HTMLFredAddElement;
        "fred-button": HTMLFredButtonElement;
        "fred-home": HTMLFredHomeElement;
        "fred-icon": HTMLFredIconElement;
        "fred-nav": HTMLFredNavElement;
        "fred-page": HTMLFredPageElement;
        "fred-root": HTMLFredRootElement;
    }
}
declare namespace LocalJSX {
    interface FredAdd {
    }
    interface FredButton {
        "url"?: string;
    }
    interface FredHome {
    }
    interface FredIcon {
        "name"?: string;
        "size"?: 's' | 'm';
    }
    interface FredNav {
    }
    interface FredPage {
    }
    interface FredRoot {
    }
    interface IntrinsicElements {
        "fred-add": FredAdd;
        "fred-button": FredButton;
        "fred-home": FredHome;
        "fred-icon": FredIcon;
        "fred-nav": FredNav;
        "fred-page": FredPage;
        "fred-root": FredRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fred-add": LocalJSX.FredAdd & JSXBase.HTMLAttributes<HTMLFredAddElement>;
            "fred-button": LocalJSX.FredButton & JSXBase.HTMLAttributes<HTMLFredButtonElement>;
            "fred-home": LocalJSX.FredHome & JSXBase.HTMLAttributes<HTMLFredHomeElement>;
            "fred-icon": LocalJSX.FredIcon & JSXBase.HTMLAttributes<HTMLFredIconElement>;
            "fred-nav": LocalJSX.FredNav & JSXBase.HTMLAttributes<HTMLFredNavElement>;
            "fred-page": LocalJSX.FredPage & JSXBase.HTMLAttributes<HTMLFredPageElement>;
            "fred-root": LocalJSX.FredRoot & JSXBase.HTMLAttributes<HTMLFredRootElement>;
        }
    }
}
